name = "archiscript"
version = "0.3.1"
defaultTargets = ["ArchiScript", "ArchiScriptExamples", "ArchiScriptTests"]

[[lean_lib]]
name = "ArchiScript"

[[lean_lib]]
name = "ArchiScriptExamples"

[[lean_lib]]
name = "ArchiScriptTests"
roots = ["ArchiScriptTests"]
